#include <stdio.h>
#include <conio.h>
#include <windows.h>
#include <string.h>
#include <stdlib.h>
	char mapLine00[] = {"                                                                                                                                                                                                                                                "};
	char mapLine01[] = {"                                                                                                                                                                                                                                                "};
	char mapLine02[] = {"                                                                                                                                                                                                                                                "};
	char mapLine03[] = {"                                                                                                                                                                                                                                                "};
	char mapLine04[] = {"                                                                                                                                                                                                                                                "};
	char mapLine05[] = {"                                                                                                                                                                                                                                                "};
	char mapLine06[] = {"                                                                                                                                                                                                                                                "};
	char mapLine07[] = {"                                                                                                                                                                                                                                                "};
	char mapLine08[] = {"                                      88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888                                                     "};
	char mapLine09[] = {"                                      88888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888                                                     "};
	char mapLine10[] = {"                                      8                                                                                                         _________________________________________ 8                                                     "};
	char mapLine11[] = {"                                      8                                                __________________________________________              |                                         |8                                                     "};
	char mapLine12[] = {"                                      8                                               |                                          |             |                                         |8                                                     "};
	char mapLine13[] = {"                                      8 _________________________________________     |        __________________________        |             |                                         |8                                                     "};
	char mapLine14[] = {"                                      8|                                         |    |        |           ||            |       |             |                                         |8                                                     "};
	char mapLine15[] = {"                                      8|                                         |    |        |           ||            |       |             |                                         |8                                                     "};
	char mapLine16[] = {"                                      8|                                         |    |        |___________||____________|       |             |                  ______                 |8                                                     "};
	char mapLine17[] = {"                                      8|                                         |    |                                          |             |_________________|      |________________|8                                                     "};
	char mapLine18[] = {"                                      8|                                         |    |__________________________________________|              |  |___| |___|              |___||___|  | 8                                                     "};
	char mapLine19[] = {"                                      8|                                         |    |                                          |              |            |   L E A R N  |           | 8                                                     "};
	char mapLine20[] = {"                                      8|                                         |    |              C  I  T - U                 |              |            |___        ___|           | 8                                                     "};
	char mapLine21[] = {"                                      8|_________________________________________|    |                                          |              |            |   |______|   |           | 8                                                     "};
	char mapLine22[] = {"                                      8 | |__|__|__|       |           |   |__| |     |             L I B R A R Y                |    _________ |            |              |           | 8                                                     "};
	char mapLine23[] = {"                                      8 |                  |           |        |     |                                          |   |         ||            |   ________   |           | 8                                                     "};
	char mapLine24[] = {"                                      8 |                  |___________|        |     |     _____                     _____      |   | A C A D ||            |  |        |  |           | 8                                                     "};
	char mapLine25[] = {"                                      8 |          G Y M    |  _____  |         |     |    |  |  |                   |  |  |     |   |_________||            |  |        |  |           | 8                                                     "};
	char mapLine26[] = {"                                      8 |___________________|  | | |  |_________|     |    |  |  |                   |  |  |     |     |     |  |____________|__|________|__|___________| 8                                                     "};
	char mapLine27[] = {"                                      8                     |__|_|_|__|         |     |____|__|__|___________________|__|__|_____|                                                        8                                                     "};
	char mapLine28[] = {"                                      8                                         |_________________________________________________________________________________________________________8                                                     "};
	char mapLine29[] = {"                                      8                                                                                                                                                   8                                                     "};
	char mapLine30[] = {"                                      8                                                                                                                                                   8                                                     "};
	char mapLine31[] = {"                                      8                                                                                                                                                   8                                                     "};
	char mapLine32[] = {"                                      8                                                                                                                                                   8                                                     "};
	char mapLine33[] = {"                                      8                                              ________________________________________________________              _______________________________8                                                     "};
	char mapLine34[] = {"                                      8                                             | ____________________________________________           |           ||                               8                                                     "};
	char mapLine35[] = {"                                      8                                             ||                                            |          |           ||                               8                                                     "};
	char mapLine36[] = {"                                      8                                             ||                                            |          |           ||                               8                                                     "};
	char mapLine37[] = {"                                      8                                             ||                                            |          |           ||                               8                                                     "};
	char mapLine38[] = {"                                      8                                             ||                                            |          |           ||___________                    8                                                     "};
	char mapLine39[] = {"                                      8                                             ||                                            |          |           |  | _______ |                   8                                                     "};
	char mapLine40[] = {"                                      8                                             ||                                            |          |           |  | |     | |                   8                                                     "};
	char mapLine41[] = {"                                      8 _______________________________             ||         __________________________         |          |           |  | |  L  | |                   8                                                     "};
	char mapLine42[] = {"                                      8|                               ||           ||         |                        |         |          |           |  | |     | |                   8                                                     "};
	char mapLine43[] = {"                                      8|                               ||           ||         ||_|_|_|_|_|_|_|_|_|_|_|_|         |          |           |  | |  A  | |                   8                                                     "};
	char mapLine44[] = {"                                      8|                               ||     |     ||         |________________________|         |          |     |     |  | |     | |                   8                                                     "};
	char mapLine45[] = {"                                      8|                               ||     |     ||         |                        |         |          |     |     |  | |  B  | |                   8                                                     "};
	char mapLine46[] = {"                                      8|                               ||     |     ||         |                        |         |          |     |     |  | |     | |                   8                                                     "};
	char mapLine47[] = {"                                      8|                               ||     |     ||         |________________________|         |          |     |     |  | |  A  | |                   8                                                     "};
	char mapLine48[] = {"                                      8|     ____________________      ||           ||____________________________________________|          |           |  | |     | |                   8                                                     "};
	char mapLine49[] = {"                                      8|    |         |          |     ||           ||                                            |          |           |  | |  N  | |                   8                                                     "};
	char mapLine50[] = {"                                      8|    |         |          |     ||     |     ||                                            |          |     |     |  | |_____| |                   8                                                     "};
	char mapLine51[] = {"                                      8|    |         |          |     ||     |     ||                                            |          |     |     |  |         |                   8                                                     "};
	char mapLine52[] = {"                                      8|    |_________|__________|     ||     |     ||                                            |          |     |     |  |         |                   8                                                     "};
	char mapLine53[] = {"                                      8|                               ||     |     ||____________________________________________|          |     |     |  |_________|                   8                                                     "};
	char mapLine54[] = {"                                      8|                               ||           ||   _____           _____           _____    |          |           |            |                   8                                                     "};
	char mapLine55[] = {"                                      8|                               ||           ||   |_|_|           |_|_|           |_|_|    |          |           |            |                   8                                                     "};
	char mapLine56[] = {"                                      8|                               ||     |     ||                                            |          |     |     |            |                   8                                                     "};
	char mapLine57[] = {"                                      8|                               ||     |     ||   _____           _____           _____    |          |     |     |            |                   8                                                     "};
	char mapLine58[] = {"                                      8|                               ||     |     ||   |_|_|           |_|_|           |_|_|    |          |     |     |            |                   8                                                     "};
	char mapLine59[] = {"                                      8|                               ||     |     ||                                            |          |     |     |            |                   8                                                     "};
	char mapLine60[] = {"                                      8|     ____________________      ||           ||   _____           _____           _____    |          |           | ___________|                   8                                                     "};
	char mapLine61[] = {"                                      8|    |         |          |     ||           ||   |_|_|           |_|_|           |_|_|    | _______  |           ||                               8                                                     "};
	char mapLine62[] = {"                                      8|    |         |          |     ||     |     ||                  _______                   ||       | |     |     ||                               8                                                     "};
	char mapLine63[] = {"                                      8|    |         |          |     ||     |     ||   _____          |_____|          _____    || R T L | |     |     ||                               8                                                     "};
	char mapLine64[] = {"                                      8|    |_________|__________|     ||     |     ||   |_|_|          ||   ||          |_|_|    ||_______| |     |     ||                               8                                                     "};
	char mapLine65[] = {"                                      8|                               ||     |     ||__________________||___||___________________|  |   |   |     |     ||                               8                                                     "};
	char mapLine66[] = {"                                      8|                               ||           |________________________________________________________|           ||_______________________________8                                                     "};
	char mapLine67[] = {"                                      8|_______________________________||                                                                                |  | ___________________________ 8                                                     "};
	char mapLine68[] = {"                                      8|                       |     | ||                                                                                |  | |     |___________________| 8                                                     "};
	char mapLine69[] = {"                                      8|                       |_____| ||                                                                                |  | |  W  |____________________ 8                                                     "};
	char mapLine70[] = {"                                      8|   ALLIED BUILDING     |  |  | ||                                                                                |  | |     |___________________| 8                                                    "};
	char mapLine71[] = {"                                      8|_______________________|__|__|_||_________________________________________________                    ___________|  | |  I  |____________________ 8                                                     "};
	char mapLine72[] = {"                                      8                                                                                  8|                  |              | |     |___________________| 8                                                     "};
	char mapLine73[] = {"                                      8                                                                                  8|        |         |              | |  L  |____________________ 8                                                     "};
	char mapLine74[] = {"                                      8                                                                                  8|        |         |              | |     |___________________| 8                                                     "};
	char mapLine75[] = {"                                      8                                                                                  8|        |         |              | |  D  |____________________ 8                                                    "};
	char mapLine76[] = {"                                      8                                                                                  8|        |         |              | |     |___________________| 8                                                     "};
	char mapLine77[] = {"                                      8                                                                                  8|                  |              | |  C  |____________________ 8                                                     "};
	char mapLine78[] = {"                                      8                                                                                  8|                  |              | |     |___________________| 8                                                     "};
	char mapLine79[] = {"                                      8                                                                                  8|        |         |              | |  A  |____________________ 8                                                     "};
	char mapLine80[] = {"                                      8                                                                                  8|        |         |      _______ | |     |___________________| 8                                                     "};
	char mapLine81[] = {"                                      8                                                                                  8|        |         |     |       || |  T  |                     8                                                     "};
	char mapLine82[] = {"                                      8 _____________________________________________________________________            8|        |         |     | G L E || |     |   __________        8                                                     "};
	char mapLine83[] = {"                                      8 ______________________________________                               |           8|                  |     |_______|| |  S  |   |   ||   |        8                                                     "};
	char mapLine84[] = {"                                      8|             ____________             |                              |           8|                  |       |   |  |_|_____|___|___||___|________8                                                     "};
	char mapLine85[] = {"                                      8|            |            |            |                              |           8|        |         |                                            8                                                     "};
	char mapLine86[] = {"                                      8|            |____________|            |                              |           8|        |         |                                            8                                                     "};
	char mapLine87[] = {"                                      8|______________________________________|                              |           8|        |         |                                            8                                                     "};
	char mapLine88[] = {"                                      8|             ____________             |                              |           8|        |         |                                            8                                                     "};
	char mapLine89[] = {"                                      8|            |_|___||___|_|            |                              |           8|                  |                                            8                                                     "};
	char mapLine90[] = {"                                      8|            |_|___||___|_|            |                              |           8|                  |                                            8                                                     "};
	char mapLine91[] = {"                                      8|            |_|___||___|_|            |                              |           8|        |         |                                            8                                                     "};
	char mapLine92[] = {"                                      8|            |_|___||___|_|            |                              |           8|        |         |                                            8                                                     "};
	char mapLine93[] = {"                                      8|            |_|___||___|_|            |                              |           8|        |         |                                            8                                                     "};
	char mapLine94[] = {"                                      8|            |_|___||___|_|            |                              |           8|        |         |                                            8                                                     "};
	char mapLine95[] = {"                                      8|            |_|___||___|_|            |                              |           8|                  |                                            8                                                     "};
	char mapLine96[] = {"                                      8|            |_|___||___|_|            | _______                      |           8|                  |                                            8                                                     "};
	char mapLine97[] = {"                                      8|            |_|___||___|_|            ||       |                     |           8|        |         |                                            8                                                     "};
	char mapLine98[] = {"                                      8|      _____ |_|___||___|_| _____      || N G E |                     |           8|        |         |                                            8                                                     "};
	char mapLine99[] = {"                                      8|      | | | |_|___||___|_| | | |      ||_______|                     |           8|        |         |                                            8                                                     "};
   char mapLine100[] = {"                                      8|______|_|_|_|_|___||___|_|_|_|_|______|  |   |                       |           8|        |         |                                            8                                                     "};
   char mapLine101[] = {"                                      8                                                                      |           8|                  |                                            8                                                     "};
   char mapLine102[] = {"                                      8                                                                      |           8|                  |                                            8                                                     "};
   char mapLine103[] = {"                                      8                                                                      |           8|        |         |                                            8                                                     "};
   char mapLine104[] = {"                                      8                                                                      |           8|        |         |                                            8                                                     "};
   char mapLine105[] = {"                                      88888888888888888888888888888888888888888888888888888888888888888888888888      8888|        |         |888888888888888888888888888888888888888888888                                                     "};
   char mapLine106[] = {"                                      88888888888888888888888888888888888888888888888888888888888888888888888888      8888|        |         |888888888888888888888888888888888888888888888                                                     "};
   char mapLine107[] = {"                                                                                                                                                                                                                                              "};
   char mapLine108[] = {"                                                                                                                                                                                                                                              "};
   char mapLine109[] = {"                                                                                                                                                                                                                                              "};
   char mapLine110[] = {"                                                                                                                                                                                                                                              "};
   char mapLine111[] = {"                                                                                                                                                                                                                                              "};
   char mapLine112[] = {"                                                                                                                                                                                                                                              "};
   char mapLine113[] = {"                                                                                                                                                                                                                                              "};
   char mapLine114[] = {"                                                                                                                                                                                                                                              "};
   char mapLine115[] = {"                                                                                                                                                                                                                                              "};

char mapLines[114][220];
void copyLines(){
	
strcpy(mapLines[0], mapLine00);
strcpy(mapLines[1], mapLine01);
strcpy(mapLines[2], mapLine02);
strcpy(mapLines[3], mapLine03);
strcpy(mapLines[4], mapLine04);
strcpy(mapLines[5], mapLine05);
strcpy(mapLines[6], mapLine06);
strcpy(mapLines[7], mapLine07);
strcpy(mapLines[8], mapLine08);
strcpy(mapLines[9], mapLine09);
strcpy(mapLines[10], mapLine10);
strcpy(mapLines[11], mapLine11);
strcpy(mapLines[12], mapLine12);
strcpy(mapLines[13], mapLine13);
strcpy(mapLines[14], mapLine14);
strcpy(mapLines[15], mapLine15);
strcpy(mapLines[16], mapLine16);
strcpy(mapLines[17], mapLine17);
strcpy(mapLines[18], mapLine18);
strcpy(mapLines[19], mapLine19);
strcpy(mapLines[20], mapLine20);
strcpy(mapLines[21], mapLine21);
strcpy(mapLines[22], mapLine22);
strcpy(mapLines[23], mapLine23);
strcpy(mapLines[24], mapLine24);
strcpy(mapLines[25], mapLine25);
strcpy(mapLines[26], mapLine26);
strcpy(mapLines[27], mapLine27);
strcpy(mapLines[28], mapLine28);
strcpy(mapLines[29], mapLine29);
strcpy(mapLines[30], mapLine30);
strcpy(mapLines[31], mapLine31);
strcpy(mapLines[32], mapLine32);
strcpy(mapLines[33], mapLine33);
strcpy(mapLines[34], mapLine34);
strcpy(mapLines[35], mapLine35);
strcpy(mapLines[36], mapLine36);
strcpy(mapLines[37], mapLine37);
strcpy(mapLines[38], mapLine38);
strcpy(mapLines[39], mapLine39);
strcpy(mapLines[40], mapLine40);
strcpy(mapLines[41], mapLine41);
strcpy(mapLines[42], mapLine42);
strcpy(mapLines[43], mapLine43);
strcpy(mapLines[44], mapLine44);
strcpy(mapLines[45], mapLine45);
strcpy(mapLines[46], mapLine46);
strcpy(mapLines[47], mapLine47);
strcpy(mapLines[48], mapLine48);
strcpy(mapLines[49], mapLine49);
strcpy(mapLines[50], mapLine50);
strcpy(mapLines[51], mapLine51);
strcpy(mapLines[52], mapLine52);
strcpy(mapLines[53], mapLine53);
strcpy(mapLines[54], mapLine54);
strcpy(mapLines[55], mapLine55);
strcpy(mapLines[56], mapLine56);
strcpy(mapLines[57], mapLine57);
strcpy(mapLines[58], mapLine58);
strcpy(mapLines[59], mapLine59);
strcpy(mapLines[60], mapLine60);
strcpy(mapLines[61], mapLine61);
strcpy(mapLines[62], mapLine62);
strcpy(mapLines[63], mapLine63);
strcpy(mapLines[64], mapLine64);
strcpy(mapLines[65], mapLine65);
strcpy(mapLines[66], mapLine66);
strcpy(mapLines[67], mapLine67);
strcpy(mapLines[68], mapLine68);
strcpy(mapLines[69], mapLine69);
strcpy(mapLines[70], mapLine70);
strcpy(mapLines[71], mapLine71);
strcpy(mapLines[72], mapLine72);
strcpy(mapLines[73], mapLine73);
strcpy(mapLines[74], mapLine74);
strcpy(mapLines[75], mapLine75);
strcpy(mapLines[76], mapLine76);
strcpy(mapLines[77], mapLine77);
strcpy(mapLines[78], mapLine78);
strcpy(mapLines[79], mapLine79);
strcpy(mapLines[80], mapLine80);
strcpy(mapLines[81], mapLine81);
strcpy(mapLines[82], mapLine82);
strcpy(mapLines[83], mapLine83);
strcpy(mapLines[84], mapLine84);
strcpy(mapLines[85], mapLine85);
strcpy(mapLines[86], mapLine86);
strcpy(mapLines[87], mapLine87);
strcpy(mapLines[88], mapLine88);
strcpy(mapLines[89], mapLine89);
strcpy(mapLines[90], mapLine90);
strcpy(mapLines[91], mapLine91);
strcpy(mapLines[92], mapLine92);
strcpy(mapLines[93], mapLine93);
strcpy(mapLines[94], mapLine94);
strcpy(mapLines[95], mapLine95);
strcpy(mapLines[96], mapLine96);
strcpy(mapLines[97], mapLine97);
strcpy(mapLines[98], mapLine98);
strcpy(mapLines[99], mapLine99);
strcpy(mapLines[100], mapLine100);
strcpy(mapLines[101], mapLine101);
strcpy(mapLines[102], mapLine102);
strcpy(mapLines[103], mapLine103);
strcpy(mapLines[104], mapLine104);
strcpy(mapLines[105], mapLine105);
strcpy(mapLines[106], mapLine106);
strcpy(mapLines[107], mapLine107);
strcpy(mapLines[108], mapLine108);
strcpy(mapLines[109], mapLine109);
strcpy(mapLines[110], mapLine110);
strcpy(mapLines[111], mapLine111);
strcpy(mapLines[112], mapLine112);
strcpy(mapLines[113], mapLine113);
strcpy(mapLines[114], mapLine114);
strcpy(mapLines[115], mapLine115);
}




